#!/usr/bin/env python3
"""Generate one noise-config YAML per (modality, effect) pair.

The robustness study runs each corruption in isolation — one effect, one
modality, everything else clean — so any change in detections is attributable
to that single corruption. This emits the 12 configs of the canonical taxonomy
(4 effects x 3 modalities; see docs/vAIlt/04_Design/noise-injection-design.md)
into configs/noise/single/.

Parameter values come from outputs/noise_visual_inspection/effect_parameters.yaml
(the v2 single-level realized parameters), except frame_deletion, which uses
`interval: 2` rather than the visual-inspection `index_list: [0]` so that on a
short run it actually fires on more than one frame. Note frame_deletion keys
off the real K-Radar sensor index in meta['idx'][modality], not the 0..N-1
loop counter.

Usage:
    python scripts/alvis/gen_single_effect_configs.py
"""
from __future__ import annotations

import os

OUT_DIR = os.path.join("configs", "noise", "single")

# (effect_name, params, note) per modality.
EFFECTS: dict[str, list[tuple[str, dict, str]]] = {
    "radar": [
        ("frame_deletion", {"mode": "deterministic", "interval": 2},
         "radar drops every 2nd frame; sets rdr_sparse to None -> blackout policy applies"),
        ("noise_induced_shifts", {"shift_std": 2.0, "distribution": "gaussian"},
         "each radar detection displaced by N(0, 2.0 m); shape preserved"),
        ("loss_partial", {"fraction": 0.5},
         "half the radar detections zeroed in place; row count preserved"),
        # NOTE: loss_complete is redundant with frame_deletion at interval 1 --
        # both call _set_none unconditionally vs. behind a frame gate. See
        # docs/vAIlt/04_Design/Noise_Taxonomy.md:19, which excludes it from the
        # canonical taxonomy. Kept generated for back-compat; prefer
        # frame_deletion with `interval: 1` for total sensor failure.
        ("loss_complete", {},
         "radar delivers nothing; REDUNDANT with frame_deletion interval:1"),
    ],
    "lidar": [
        ("frame_deletion", {"mode": "deterministic", "interval": 2},
         "lidar drops every 2nd frame; sets ldr64 to None -> blackout policy applies"),
        ("gaussian_noise", {"sigma_xy": 0.5, "sigma_z": 0.2},
         "additive N(0, sigma) on lidar xyz; shape preserved"),
        ("loss_partial", {"fraction": 0.5},
         "half the lidar points zeroed in place; row count preserved"),
        ("loss_complete", {},
         "lidar delivers nothing; sets ldr64 to None -> blackout policy applies"),
    ],
    "camera": [
        ("frame_deletion", {"mode": "deterministic", "interval": 2},
         "camera drops every 2nd frame; writes a black-image tensor, never None"),
        ("gaussian_noise", {"sigma": 40},
         "additive N(0, 40) in 0-255 image units"),
        ("loss_partial", {"fraction": 0.3},
         "a contiguous 30% rectangle of the image blacked out"),
        ("loss_complete", {},
         "camera dead; writes a black-image tensor, never None"),
    ],
}

HEADER = """\
# Single-corruption run: {modality} / {effect}
#
# {note}
#
# Exactly one effect on exactly one modality -- every other sensor is clean --
# so any change in detections versus the clean baseline is attributable to this
# corruption alone. Generated by scripts/alvis/gen_single_effect_configs.py;
# edit that file rather than this one.
seed: 42
"""


def _fmt_params(params: dict) -> str:
    if not params:
        return "    params: {}\n"
    lines = ["    params:\n"]
    for k, v in params.items():
        lines.append(f"      {k}: {v}\n")
    return "".join(lines)


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    written = []
    for modality, effects in EFFECTS.items():
        for effect, params, note in effects:
            body = HEADER.format(modality=modality, effect=effect, note=note)
            for m in ("radar", "lidar", "camera"):
                if m != modality:
                    body += f"{m}: []\n"
                    continue
                body += f"{m}:\n  - name: {effect}\n    p: 1.0\n"
                body += _fmt_params(params)
            path = os.path.join(OUT_DIR, f"{modality}_{effect}.yml")
            with open(path, "w") as f:
                f.write(body)
            written.append(path)
    print(f"Wrote {len(written)} configs to {OUT_DIR}/")
    for p in sorted(written):
        print(f"  {p}")


if __name__ == "__main__":
    main()
